[package]
name = "revision2020"
version = "0.1.0"
authors = ["Tom Barrett <tom@tombarrett.xyz>"]
edition = "2018"

[dependencies]
luminance = "0.39"
luminance-derive = "0.5.3"
luminance-glfw = "0.12.1"
alto = "3.0.4"
lewton = "0.10.0"
